#
# Module manifest for module 'SqlDeploymentPowerShell'
#
# Generated by: abfyles
#
# Generated on: 3/25/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SqlDeploy.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '8f14b69b-d14d-42c9-b683-99b04947fb79'

# Author of this module
Author = 'abfyles'

# Company or vendor of this module
CompanyName = 'Fyles and Associates Consulting LLC'

# Copyright statement for this module
Copyright = 'Attribution-ShareAlike 4.0 International'

# Description of the functionality provided by this module
Description = 'Powershell module for the deployment of DAC and ISPACs to SQL'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("SQLPS")

# Assemblies that must be loaded prior to importing this module
 RequiredAssemblies = @("System.dll")

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @("SSISPS.psm1", "IsPacDeploy.psm1", "DacPacDeploy.psm1")

# Functions to export from this module
FunctionsToExport = '*-*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module.
 ModuleList = @("SqlDeploy.psm1","SSISPS.psm1","DacPacDeploy.psm1")

# List of all files packaged with this module
# FileList = @("Common.ps1")

# Private data to pass to the module specified in RootModule/ModuleToProcess
#PrivateData = @{}

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

